#ifndef __ROM_WIFI_HAL_MEDIA_ACCESS_H__
#define __ROM_WIFI_HAL_MEDIA_ACCESS_H__

#define RT_BCN_DMA_INT_MASKS			(BIT_SETBCNOK0_EN | BIT_SETBCNERR0_EN)
#define RT_BCN_INT_HIMR0_MASKS			(BIT_TXBCN1_ERR_INT_EN | BIT_TXBCN1_OK_INT_EN )
#define RT_BCN_INT_HIMR1_MASKS			(BIT_BCNERLY0_INT_EN | BIT_BCNERLY8_INT_EN | BIT_TXBCNERE9_INT_EN | BIT_TXBCNOK9_INT_EN)

#endif

