name=AmebaSPI
version=1.0.0
author=Realtek
maintainer=Realtek <ameba.arduino@gmail.com>
sentence=Enables the communication with devices that use the Serial Peripheral Interface (SPI) Bus.
paragraph=
category=Communication
url=http://www.amebaiot.com/ameba-arduino-peripherals-examples/
architectures=ameba
