#ifndef _ST7262_H_
#define _ST7262_H_

#define LCDC_COLOR_DEPTH            COLOR_DEPTH_24
#define LCDC_RGB_VSW                1
#define LCDC_RGB_VBP                4
#define LCDC_RGB_VFP                6
#define LCDC_RGB_HSW                4
#define LCDC_RGB_HBP                40
#define LCDC_RGB_HFP                40
#define LCDC_INTERFACE              RGB
#define LCDC_INTERFACE_WIDTH        LCDC_RGB_IF_24_BIT
#define LCDC_WIDTH                  800
#define LCDC_HEIGHT                 480
#define LCDC_RGB_ENABLE_POLAR       LCDC_RGB_EN_PUL_HIGH_LEV_ACTIVE
#define LCDC_RGB_DCLK_ACTIVE_EDGE   LCDC_RGB_DCLK_FALLING_EDGE_FETCH
#define LCDC_RGB_HS_POLAR           LCDC_RGB_HS_PUL_LOW_LEV_SYNC
#define LCDC_RGB_VS_POLAR           LCDC_RGB_VS_PUL_LOW_LEV_SYNC
#define LCDC_RGB_REFRESH_FREQ       40

LCD_PIN_DEF_START
LCD_PIN_DEF(LCD_D0, AMB_D23)
LCD_PIN_DEF(LCD_D1, AMB_D22)
LCD_PIN_DEF(LCD_D2, AMB_D25)
LCD_PIN_DEF(LCD_D3, AMB_D24)
LCD_PIN_DEF(LCD_D4, AMB_D26)
LCD_PIN_DEF(LCD_D5, AMB_D28)
LCD_PIN_DEF(LCD_D6, AMB_D27)
LCD_PIN_DEF(LCD_D7, AMB_D29)
LCD_PIN_DEF(LCD_D8, AMB_D14)
LCD_PIN_DEF(LCD_D9, AMB_D16)
LCD_PIN_DEF(LCD_D10, AMB_D15)
LCD_PIN_DEF(LCD_D11, AMB_D17)
LCD_PIN_DEF(LCD_D12, AMB_D19)
LCD_PIN_DEF(LCD_D13, AMB_D18)
LCD_PIN_DEF(LCD_D14, AMB_D20)
LCD_PIN_DEF(LCD_D15, AMB_D21)
LCD_PIN_DEF(LCD_D16, AMB_D2)
LCD_PIN_DEF(LCD_D17, AMB_D4)
LCD_PIN_DEF(LCD_D18, AMB_D6)
LCD_PIN_DEF(LCD_D19, AMB_D8)
LCD_PIN_DEF(LCD_D20, AMB_D10)
LCD_PIN_DEF(LCD_D21, AMB_D11)
LCD_PIN_DEF(LCD_D22, AMB_D12)
LCD_PIN_DEF(LCD_D23, AMB_D13)
LCD_PIN_DEF(LCD_RGB_HSYNC, AMB_D33)
LCD_PIN_DEF(LCD_RGB_VSYNC, AMB_D34)
LCD_PIN_DEF(LCD_RGB_DCLK, AMB_D31)
LCD_PIN_DEF(LCD_RGB_DE, AMB_D36)
LCD_PIN_DEF_END

LCD_GPIO_CTRL_START
LCD_GPIO_CTRL_DEF(LCD_DISPLAY, AMB_D32, HIGH)
LCD_GPIO_CTRL_DEF(LCD_BLEN, AMB_D9, HIGH)
LCD_GPIO_CTRL_END

#endif