#ifndef _ST7272A_H_
#define _ST7272A_H_

#define LCDC_COLOR_DEPTH            COLOR_DEPTH_24
#define LCDC_RGB_VSW                4
#define LCDC_RGB_VBP                8
#define LCDC_RGB_VFP                8
#define LCDC_RGB_HSW                4
#define LCDC_RGB_HBP                39
#define LCDC_RGB_HFP                8
#define LCDC_INTERFACE              RGB
#define LCDC_INTERFACE_WIDTH        LCDC_RGB_IF_8_BIT
#define LCDC_WIDTH                  320
#define LCDC_HEIGHT                 240
#define LCDC_RGB_ENABLE_POLAR       LCDC_RGB_EN_PUL_HIGH_LEV_ACTIVE
#define LCDC_RGB_DCLK_ACTIVE_EDGE   LCDC_RGB_DCLK_FALLING_EDGE_FETCH
#define LCDC_RGB_HS_POLAR           LCDC_RGB_HS_PUL_LOW_LEV_SYNC
#define LCDC_RGB_VS_POLAR           LCDC_RGB_VS_PUL_LOW_LEV_SYNC
#define LCDC_RGB_REFRESH_FREQ       35

LCD_PIN_DEF_START
LCD_PIN_DEF(LCD_D0, AMB_D9)
LCD_PIN_DEF(LCD_D1, AMB_D13)
LCD_PIN_DEF(LCD_D2, AMB_D7)
LCD_PIN_DEF(LCD_D3, AMB_D8)
LCD_PIN_DEF(LCD_D4, AMB_D11)
LCD_PIN_DEF(LCD_D5, AMB_D15)
LCD_PIN_DEF(LCD_D6, AMB_D12)
LCD_PIN_DEF(LCD_D7, AMB_D14)
LCD_PIN_DEF(LCD_RGB_HSYNC, AMB_D10)
LCD_PIN_DEF(LCD_RGB_VSYNC, AMB_D4)
LCD_PIN_DEF(LCD_RGB_DCLK, AMB_D6)
LCD_PIN_DEF_END

LCD_GPIO_CTRL_START
LCD_GPIO_CTRL_DEF(LCD_RESET, AMB_D5, HIGH)
LCD_GPIO_CTRL_DEF(LCD_BLEN, AMB_D2, HIGH)
LCD_GPIO_CTRL_END

#endif