#ifndef __ROM_WIFI_HAL_MEDIA_ACCESS_H__
#define __ROM_WIFI_HAL_MEDIA_ACCESS_H__

#define RT_BCN_DMA_INT_MASKS			(BIT_SETBCNOK0_EN | BIT_SETBCNERR0_EN)
#define RT_BCN_INT_HIMR0_MASKS			(BIT_HS_TXBCN1_ERR_INT_EN | BIT_HS_TXBCN1_OK_INT_EN )
#define RT_BCN_INT_HIMR1_MASKS			(BIT_HS_BCNERLY0_INT_EN | BIT_HS_BCNERLY8_INT_EN | BIT_HS_TXBCNERE9_INT_EN | BIT_HS_TXBCNOK9_INT_EN)

/*************CONFIG_ADDRESS_CAM************/
union addr_cam_entry {
	struct {
		u32 a3: 4;
		u32 a2: 4;
		u32 a1: 4;
		u32 uc: 1;
		u32 mc: 1;
		u32 bc: 1;
		u32 subtype: 4;
		u32 ctrl: 1;
		u32 mgnt: 1;
		u32 data: 1;
		u32 rsvd: 4;
		u32 relay: 1;
		u32 ul: 1;
		u32 normal: 1;
		u32 no_a2: 1;
		u32 subtype_mask : 1;
		u32 valid: 1;
	};
	u32 entry;
};

#define ADDRCAM_SUBTYPE_MASK	BIT(30)
#define ADDRCAM_NO_A2			BIT(29)
#define ADDRCAM_NORMAL			BIT(28)
#define ADDRCAM_UL				BIT(27)
#define ADDRCAM_RELAY			BIT(26)
//#define ADDRCAM_RSVD_SHIFT	22
#define ADDRCAM_DATA			BIT(21)
#define ADDRCAM_MGNT			BIT(20)
#define ADDRCAM_CTRL			BIT(19)
#define ADDRCAM_SUBTYPE_SHIFT	15
#define ADDRCAM_BC				BIT(14)
#define ADDRCAM_MC				BIT(13)
#define ADDRCAM_UC				BIT(12)
#define ADDRCAM_A1_SHIFT		8
#define ADDRCAM_A2_SHIFT		4
#define ADDRCAM_A3_SHIFT		0

enum ADDR_CAM_ENTRY_IDX {
	ADDR_CAM_IDX_SCAN_BCN = 0,
	ADDR_CAM_IDX_SCAN_PROBE = 1,
	ADDR_CAM_IDX_STA = 2,
	ADDR_CAM_IDX_PROBE_REQ = 3,
	ADDR_CAM_IDX_PS_POLL = 4,
	ADDR_CAM_IDX_AP = 5,
	ADDR_CAM_IDX_PROMISC_ALL = 6,
	ADDR_CAM_IDX_PROMISC_A2 = 7,
	ADDR_CAM_IDX_CTRL_ALL = 8,
	ADDR_CAM_IDX_CTRL_ALL_AP = 9,
	ADDR_CAM_IDX_NAN_BCN_ALL = 10,
	ADDR_CAM_IDX_NAN_DW_FAW = 11,
	ADDR_CAM_IDX_MAX = 12,			//max num of address_cam_entry[] in ROM is 12
	ADDRCAM_IDX_MBSSID_BCN = 13,		//the idx of address_cam_ext_entry[] is from here on
	ADDRCAM_IDX_MBSSID_PROBE_RSP = 14,

	ADDR_CAM_IDX_ALL_MAX,
};

#define ADDR_CAM_BASE		0x51C00

#define ADDRCAM_ENTRY_SCAN	0x0003	/*entry 0/1*/
#define ADDRCAM_ENTRY_STA	0x0004	/*entry 2*/
#define ADDRCAM_ENTRY_SOFTAP	0x0038	/*entry 3/4/5*/
#define ADDRCAM_ENTRY_PROMISC_ALL	0x0040	/*entry 6*/
#define ADDRCAM_ENTRY_PROMISC_A2	0x0080	/*entry 7*/
#define ADDRCAM_ENTRY_CTRL_ALL	0x0100	/*entry 8*/
#define ADDRCAM_ENTRY_CTRL_ALL_AP	0x0200	/*entry 9*/
#define ADDRCAM_ENTRY_NAN_BCN	0x0400	/*entry 10*/
#define ADDRCAM_ENTRY_NAN_DW_FAW	0x0800	/*entry 11*/

#define ADDRCAM_ENTRY_ALL	0x3fff	/*entry 0~13*/

/*P2P related*/
#define ADDRCAM_P2P_MAC0_FILTER	ADDRCAM_NORMAL | ADDRCAM_MGNT | ADDRCAM_UC | (ADDRCAM_TABLE_INDEX_MAC0) << ADDRCAM_A1_SHIFT
#define ADDRCAM_P2P_MAC1_FILTER	ADDRCAM_NORMAL | ADDRCAM_MGNT | ADDRCAM_UC | (ADDRCAM_TABLE_INDEX_MAC1) << ADDRCAM_A1_SHIFT
#define ADDRCAM_ENTRY_P2P_SCAN		0x00C9	/*entry 0/3/6/7*/
#define ADDRCAM_ENTRY_P2P_DEV_WITH_GO		0x0040 /*entry 6*/
#define ADDRCAM_ENTRY_P2P_DEV_WITH_GC		0x0080 /*entry 7*/
#define ADDRCAM_ENTRY_PROBE_REQ		0x0008 /*entry3*/

#define ADDRCAM_TABLE_INDEX_ALL_FIT	0x0
#define ADDRCAM_TABLE_INDEX_REFUGEE	0x1
#define ADDRCAM_TABLE_INDEX_MBID		0x2
#define ADDRCAM_TABLE_INDEX_MAC0 	0x3
#define ADDRCAM_TABLE_INDEX_BSSID0 	0x4
#define ADDRCAM_TABLE_INDEX_MAC1 	0x5
#define ADDRCAM_TABLE_INDEX_BSSID1_OR_FATHER_NODE 	0x6
#define ADDRCAM_TABLE_INDEX_USER_DEFINE_0 	0x7	//used by mbssid
#define ADDRCAM_TABLE_INDEX_USER_DEFINE_1 	0x8
#define ADDRCAM_TABLE_INDEX_MACID_NAN	 	0x9
#define ADDRCAM_TABLE_INDEX_BSSID_NAN	 	0xA
#define ADDRCAM_TABLE_INDEX_TA_NAN		 	0xB
#define ADDRCAM_TABLE_INDEX_BSSID_NAN_HIGH	0xC

#define ADDRCAM_ENTRY_MBSSID		(BIT(ADDRCAM_IDX_MBSSID_BCN) | BIT(ADDRCAM_IDX_MBSSID_PROBE_RSP))


/************* CONFIG_ADDRESS_CAM END ************/

#endif
