#ifndef __ROM_WIFI_HAL_MEDIA_ACCESS_H__
#define __ROM_WIFI_HAL_MEDIA_ACCESS_H__

#define RT_BCN_DMA_INT_MASKS	(BIT_AXI_BCNDOK0_IMR | BIT_AXI_BCNDERR0_IMR)
#define RT_BCN_TX_INT_MASKS     (BIT_BCNERLY0_MSK | BIT_TXBCN0_ERR_MSK | BIT_TXBCN0_OK_MSK  | BIT_BCNERLY8_MSK)

#endif
