#ifndef AMEBA_DVP_TEST_H
#define AMEBA_DVP_TEST_H

#include "sccb.h"
#include "./include/sensor.h"

// #define DVP_BITFILE_BEFORE_MANNUAL_ECO
#define GPIO_SENSOR_RWDN_PIN	_PC_9
#define GPIO_SENSOR_RESET_PIN	_PC_8

enum DVP_SCALE_TEST_CASE {
	DVP_SCALE_NONE = 0,
	DVP_CROP_X_ONLY,
	DVP_CROP_Y_ONLY,
	DVP_CROP_X_AND_Y,

	DVP_SUBSAMPLE_X_ONLY = 4,
	DVP_SUBSAMPLE_Y_ONLY,
	DVP_SUBSAMPLE_X_AND_Y,

	DVP_CROP_SUBSAMPLE_BOTH
};

enum DVP_OV5640_TEST_CASE {
	DVP_OV5640_JPG_MODE_1 = 1,
	DVP_OV5640_JPG_MODE_2,
	DVP_OV5640_JPG_MODE_3,
	DVP_OV5640_JPG_MODE_4,
	DVP_OV5640_JPG_MODE_5,
	DVP_OV5640_JPG_MODE_6,

	DVP_OV5640_YUV_MODE_BASIC = 10,			/* YUYV; pclk-vsync-hsync: 1-0-1 */
	DVP_OV5640_YUV_MODE_POLAR_INVERSE = 11,	/* pclk-vsync-hsync: 0-1-0 */

	DVP_OV5640_YUV_MODE_YVYU = 21,
	DVP_OV5640_YUV_MODE_UYVY,	//22
	DVP_OV5640_YUV_MODE_VYUY,	//23

};

#endif