/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOICERPCBASEDS_H_RPCGEN
#define _VOICERPCBASEDS_H_RPCGEN

#include "rpc_struct.h"

#include "VoiceRPCBaseDS_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>

/* the xdr functions */
extern  bool_t xdr_VOICE_KWS_CONFIG (XDR *, VOICE_KWS_CONFIG*);
extern  bool_t xdr_VOICE_RPC_INIT (XDR *, VOICE_RPC_INIT*);
extern  bool_t xdr_VOICE_RPC_WAKEUP_RESULT (XDR *, VOICE_RPC_WAKEUP_RESULT*);
extern  bool_t xdr_VOICE_RPC_ASR_RESULT (XDR *, VOICE_RPC_ASR_RESULT*);
extern  bool_t xdr_VOICE_RPC_VAD_RESULT (XDR *, VOICE_RPC_VAD_RESULT*);
extern  bool_t xdr_VOICE_RPC_AFE_RESULT (XDR *, VOICE_RPC_AFE_RESULT*);
extern  bool_t xdr_VOICE_RPC_ERROR_STATE (XDR *, VOICE_RPC_ERROR_STATE*);

#ifdef __cplusplus
}
#endif

#endif /* !_VOICERPCBASEDS_H_RPCGEN */
