/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOICERPCBASEDS_DATA_H_RPCGEN
#define _VOICERPCBASEDS_DATA_H_RPCGEN

#include <RPCBaseDS.h>

struct VOICE_KWS_CONFIG {
	uint32_t key_words;
	uint32_t key_words_length;
	uint32_t key_words_num;
	uint32_t thresholds;
	long thresholds_length;
};
typedef struct VOICE_KWS_CONFIG VOICE_KWS_CONFIG;

struct VOICE_RPC_INIT {
	int32_t voice_iface_flag;
	uint32_t mic_data_addr;
	long mic_data_length;
	VOICE_KWS_CONFIG kws_config;
};
typedef struct VOICE_RPC_INIT VOICE_RPC_INIT;

struct VOICE_RPC_WAKEUP_RESULT {
	int32_t key_words_id;
};
typedef struct VOICE_RPC_WAKEUP_RESULT VOICE_RPC_WAKEUP_RESULT;

struct VOICE_RPC_ASR_RESULT {
	int32_t len;
	uint32_t msg_addr;
};
typedef struct VOICE_RPC_ASR_RESULT VOICE_RPC_ASR_RESULT;

struct VOICE_RPC_VAD_RESULT {
	int32_t status;
	uint32_t offset_ms;
};
typedef struct VOICE_RPC_VAD_RESULT VOICE_RPC_VAD_RESULT;

struct VOICE_RPC_AFE_RESULT {
	int32_t ch_num;
	long out_others_json;
	long out_others_json_length;
	uint32_t afe_data_addr;
	long afe_data_length;
};
typedef struct VOICE_RPC_AFE_RESULT VOICE_RPC_AFE_RESULT;

struct VOICE_RPC_ERROR_STATE {
	long type;
	long state;
};
typedef struct VOICE_RPC_ERROR_STATE VOICE_RPC_ERROR_STATE;

#endif /* !_VOICERPCBASEDS_DATA_H_RPCGEN */
