/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOICERPC_AGENT_H_RPCGEN
#define _VOICERPC_AGENT_H_RPCGEN

#include "rpc_struct.h"

#include "VoiceRPC_Agent_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>
#include <VoiceRPCBaseDS.h>

#define VOICE_AGENT 3002
#define VERSION 0

struct REG_STRUCT * VOICE_AGENT_0_register(struct REG_STRUCT *rnode);
#define VOICE_RPC_ToSystem_VAD_Callback 1
extern  HRESULT * VOICE_RPC_ToSystem_VAD_Callback_0(VOICE_RPC_VAD_RESULT *, CLNT_STRUCT *);
extern  HRESULT * VOICE_RPC_ToSystem_VAD_Callback_0_svc(VOICE_RPC_VAD_RESULT *, RPC_STRUCT *, HRESULT *);
extern  HRESULT * (*p_VOICE_RPC_ToSystem_VAD_Callback_0_svc)(VOICE_RPC_VAD_RESULT *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToSystem_WAKEUP_Callback 2
extern  HRESULT * VOICE_RPC_ToSystem_WAKEUP_Callback_0(VOICE_RPC_WAKEUP_RESULT *, CLNT_STRUCT *);
extern  HRESULT * VOICE_RPC_ToSystem_WAKEUP_Callback_0_svc(VOICE_RPC_WAKEUP_RESULT *, RPC_STRUCT *, HRESULT *);
extern  HRESULT * (*p_VOICE_RPC_ToSystem_WAKEUP_Callback_0_svc)(VOICE_RPC_WAKEUP_RESULT *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToSystem_ASR_Callback 3
extern  HRESULT * VOICE_RPC_ToSystem_ASR_Callback_0(VOICE_RPC_ASR_RESULT *, CLNT_STRUCT *);
extern  HRESULT * VOICE_RPC_ToSystem_ASR_Callback_0_svc(VOICE_RPC_ASR_RESULT *, RPC_STRUCT *, HRESULT *);
extern  HRESULT * (*p_VOICE_RPC_ToSystem_ASR_Callback_0_svc)(VOICE_RPC_ASR_RESULT *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToSystem_ASR_REC_TIMEOUT_Callback 4
extern  HRESULT * VOICE_RPC_ToSystem_ASR_REC_TIMEOUT_Callback_0(long *, CLNT_STRUCT *);
extern  HRESULT * VOICE_RPC_ToSystem_ASR_REC_TIMEOUT_Callback_0_svc(long *, RPC_STRUCT *, HRESULT *);
extern  HRESULT * (*p_VOICE_RPC_ToSystem_ASR_REC_TIMEOUT_Callback_0_svc)(long *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToSystem_AFE_Callback 5
extern  HRESULT * VOICE_RPC_ToSystem_AFE_Callback_0(VOICE_RPC_AFE_RESULT *, CLNT_STRUCT *);
extern  HRESULT * VOICE_RPC_ToSystem_AFE_Callback_0_svc(VOICE_RPC_AFE_RESULT *, RPC_STRUCT *, HRESULT *);
extern  HRESULT * (*p_VOICE_RPC_ToSystem_AFE_Callback_0_svc)(VOICE_RPC_AFE_RESULT *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToSystem_State 6
extern  HRESULT * VOICE_RPC_ToSystem_State_0(VOICE_RPC_ERROR_STATE *, CLNT_STRUCT *);
extern  HRESULT * VOICE_RPC_ToSystem_State_0_svc(VOICE_RPC_ERROR_STATE *, RPC_STRUCT *, HRESULT *);
extern  HRESULT * (*p_VOICE_RPC_ToSystem_State_0_svc)(VOICE_RPC_ERROR_STATE *, RPC_STRUCT *, HRESULT *);

#ifdef __cplusplus
}
#endif

#endif /* !_VOICERPC_AGENT_H_RPCGEN */
