
#ifndef EXAMPLE_CONFIG_H
#define EXAMPLE_CONFIG_H 1


// 802.15.4 channel used by Zigbee  <11-26> Defaults to 16.
#define ZIGBEE_CHANNEL 16

// Trace level of Zigbee stack logs.  <0-4> Possible values: 0 - disable, 1 - error, 2 - warning, 3 - info, 4 - debug. Disabled by default.
#define ZIGBEE_TRACE_LEVEL 3

// Trace mask of Zigbee stack logs.  <0-2376>
// Selectively enable Zigbee binary trace logs.
// Possible values (logical or): TRACE_SUBSYSTEM_ZCL, TRACE_SUBSYSTEM_ZDO, TRACE_SUBSYSTEM_NWK. Defaults to 0x0000.
#define ZIGBEE_TRACE_MASK 0x840


// Decide if erase persistent storage at start
#define ZIGBEE_ERASE_PERSISTENT ZB_TRUE

// Channel mask
#define ZIGBEE_CHANNEL_MASK (1<<ZIGBEE_CHANNEL)

// Endpoint id
#define ZIGBEE_ENDPOINT_ID  10

// Max children
#define ZIGBEE_MAX_CHILDREN 1

// PAN ID
#define ZIGBEE_PAN_ID   0xabcd


// ZB_ERROR_PRINT_TO_LOG  - zb_error - ZBOSS error handling helpers
#ifndef ZB_ERROR_PRINT_TO_LOG
#define ZB_ERROR_PRINT_TO_LOG 1
#endif

// CONFIG_ZBOSS_RESET_ON_ASSERT - Reset device when a ZBOSS assert occurs  <0-1>
#ifndef CONFIG_ZBOSS_RESET_ON_ASSERT
#define CONFIG_ZBOSS_RESET_ON_ASSERT 1
#endif

// CONFIG_ZBOSS_HALT_ON_ASSERT - Halt device when a ZBOSS assert occurs. Use only for testing and debugging.  <0-1>
#ifndef CONFIG_ZBOSS_HALT_ON_ASSERT
#define CONFIG_ZBOSS_HALT_ON_ASSERT 0
#endif

/* Delay between sending commands */
#define DELAY_OF_SEND_CMD (3*ZB_TIME_ONE_SECOND)

#define PROBABILITY_OF_INCORRECT_VALUE 20

#define GET_RANDOM_CMD1_MODE \
  (ZB_RANDOM_VALUE(100) < PROBABILITY_OF_INCORRECT_VALUE) ? 0xFF : \
  (ZB_RANDOM_VALUE(ZB_ZCL_CUSTOM_CLUSTER_CMD1_MODE2) + 1)

#define GET_RANDOM_CMD1_VALUE \
  (ZB_RANDOM_VALUE(100) < PROBABILITY_OF_INCORRECT_VALUE) ? 0xFF : \
  (ZB_RANDOM_VALUE(0xFF))

#define GET_RANDOM_CMD2_PARAM \
  (ZB_RANDOM_VALUE(100) < PROBABILITY_OF_INCORRECT_VALUE) ? 0xFF : \
  (ZB_RANDOM_VALUE(ZB_ZCL_CUSTOM_CLUSTER_CMD2_PARAM4) + 1)

#define GET_RANDOM_CMD2_VALUE \
  (ZB_RANDOM_VALUE(100) < PROBABILITY_OF_INCORRECT_VALUE) ? 0xFFFF : \
  (ZB_RANDOM_VALUE(0xFFFF))

#define DISABLE_DEFAULT_RESPONSE_FLAG ZB_FALSE

/* Enumeration with test steps */
typedef enum test_steps_e {
	TEST_STEP_SEND_CMD1,
	TEST_STEP_SEND_CMD2,
	TEST_STEP_SEND_CMD3,
	TEST_STEP_SEND_READ_ATTR_U8_ID,
	TEST_STEP_SEND_READ_ATTR_S16_ID,
	TEST_STEP_SEND_READ_ATTR_24BIT_ID,
	TEST_STEP_SEND_READ_ATTR_32BITMAP_ID,
	TEST_STEP_SEND_READ_ATTR_IEEE_ID,
	TEST_STEP_SEND_READ_ATTR_CHAR_STRING_ID,
	TEST_STEP_SEND_READ_ATTR_UTC_TIME_ID,
	TEST_STEP_SEND_READ_ATTR_BYTE_ARRAY_ID,
	TEST_STEP_SEND_READ_ATTR_BOOL_ID,
	TEST_STEP_SEND_READ_ATTR_128_BIT_KEY_ID,

	TEST_STEP_SEND_READ_ATTR_U8_ID_READ_ONLY,
	TEST_STEP_SEND_READ_ATTR_S16_ID_WRITE_ONLY,
	TEST_STEP_SEND_WRITE_TWO_ATTRS,
	TEST_STEP_SEND_READ_ATTR_U8_ID_READ_WRITE,
	TEST_STEP_SEND_READ_ATTR_S16_ID_READ_WRITE,

	TEST_STEP_SEND_WRITE_ATTR_U8_ID,
	TEST_STEP_SEND_WRITE_ATTR_S16_ID,
	TEST_STEP_SEND_WRITE_ATTR_24BIT_ID,
	TEST_STEP_SEND_WRITE_ATTR_32BITMAP_ID,
	TEST_STEP_SEND_WRITE_ATTR_IEEE_ID,
	TEST_STEP_SEND_WRITE_ATTR_CHAR_STRING_ID,
	TEST_STEP_SEND_WRITE_ATTR_UTC_TIME_ID,
	TEST_STEP_SEND_WRITE_ATTR_BYTE_ARRAY_ID,
	TEST_STEP_SEND_WRITE_ATTR_BOOL_ID,
	TEST_STEP_SEND_WRITE_ATTR_128_BIT_KEY_ID,
	TEST_STEP_FINISH
} test_steps_t;

#define NUMBER_TEST_STEPS 23

#endif /* #define CUSTOM_CLUSTER_ZC_H */
