#ifndef BT_CONTROLLER_LL_FEATURE_H
#define BT_CONTROLLER_LL_FEATURE_H

//BT 4.2
#define BT_LL_FEATURE_BT42_LE_DATA_LENGTH_EXTENSION              BT_CONTROLLER_CONFIG_LL_FEAT_BT42_LE_DATA_LENGTH_EXTENSION
#define BT_LL_FEATURE_BT42_SECURE_CONNECTION                     BT_CONTROLLER_CONFOG_LL_FEAT_BT42_SECURE_CONNECTION
#define BT_LL_FEATURE_BT42_LE_LINK_LAYER_PRIVACY                 BT_CONTROLLER_CONFIG_LL_FEAT_BT42_LE_LINK_LAYER_PRIVACY
#define BT_LL_FEATURE_BT42_EXTENDED_SCAN_FILTER_POLICY           BT_CONTROLLER_CONFIG_LL_FEAT_BT42_EXTENDED_SCAN_FILTER_POLICY

//BT 5.0
#define BT_LL_FEATURE_BT50_LE_2M_PHY                             BT_CONTROLLER_CONFIG_LL_FEAT_BT50_LE_2M_PHY
#define BT_LL_FEATURE_BT50_LE_CODED_PHY                          BT_CONTROLLER_CONFIG_LL_FEAT_BT50_LE_CODED_PHY
#define BT_LL_FEATURE_BT50_LE_EXT_ADV                            BT_CONTROLLER_CONFIG_LL_FEAT_BT50_LE_EXT_ADV
#define BT_LL_FEATURE_BT50_LE_CHNL_SEL_ALGO_2                    BT_CONTROLLER_CONFIG_LL_FEAT_BT50_LE_CHANNEL_SEL_ALOG_2
#define BT_LL_FEATURE_BT50_LE_PERIODIC_ADV                       BT_CONTROLLER_CONFIG_LL_FEAT_BT50_LE_PERIODIC_ADV
#endif